# Generated by Django 2.2.5 on 2019-11-09 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('start_city', models.CharField(max_length=25)),
                ('start_state', models.CharField(blank=True, max_length=25)),
                ('start_zipcode', models.CharField(blank=True, max_length=5)),
                ('destination_city', models.CharField(max_length=25)),
                ('destination_state', models.CharField(blank=True, max_length=25)),
                ('destination_zipcode', models.CharField(blank=True, max_length=5)),
                ('date_leaving', models.DateField()),
                ('return_date', models.DateField(blank=True)),
                ('spots', models.IntegerField()),
                ('driver', models.CharField(max_length=25)),
                ('notes', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
