# Generated by Django 3.1.1 on 2021-04-04 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('start_city', models.CharField(max_length=25)),
                ('start_state', models.CharField(blank=True, max_length=25)),
                ('start_zipcode', models.CharField(blank=True, max_length=5)),
                ('destination_city', models.CharField(max_length=25)),
                ('destination_state', models.CharField(blank=True, max_length=25)),
                ('destination_zipcode', models.CharField(blank=True, max_length=5)),
                ('destination_coordinates_lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('destination_coordinates_lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('start_coordinates_lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('start_coordinates_lon', models.DecimalField(decimal_places=6, default=0.0, max_digits=14)),
                ('date_leaving', models.DateField()),
                ('round_trip', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('spots', models.IntegerField()),
                ('driver', models.CharField(max_length=25)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('archived', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('archivedType', models.CharField(choices=[('VI', 'Visible'), ('HD', 'Hidden'), ('RE', 'Removed'), ('AR', 'Archived')], default='VI', max_length=2)),
                ('ride_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideSharing.ridecategory')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
