# Generated by Django 2.2.5 on 2019-11-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideitem',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
    ]
