# Generated by Django 2.2.5 on 2019-11-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0002_rideitem_round_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideitem',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
