# Generated by Django 2.2.9 on 2020-02-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0003_auto_20191113_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideitem',
            name='destination_coordinates_lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rideitem',
            name='destination_coordinates_lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
    ]
