# Generated by Django 2.2.9 on 2020-02-24 17:33

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0005_auto_20200224_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideitem',
            name='ride_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideSharing.RideCategory'),
        )

    ]
