# Generated by Django 2.2.9 on 2020-02-24 17:43
import requests
from django.db import migrations

def updateLocations(apps, schema_editor):

	RideItem = apps.get_model('rideSharing', 'RideItem')
	for ride_item in RideItem.objects.all():
		# Get location

		access_token = 'pk.eyJ1IjoiY3NjaHdhIiwiYSI6ImNrNjZxdmdsYTE5MGUzbG84Z3N1dTUzOTcifQ.DKfzMNPM0XvkkwJ-nLQDHg'

		destination_city = ride_item.destination_city
		destination_state = ride_item.destination_state
		destination_zipcode = ride_item.destination_zipcode

		locate_url = "https://api.mapbox.com/geocoding/v5/mapbox.places/" \
		+ requests.utils.quote(destination_city.strip()) + "%20" \
		+ requests.utils.quote(destination_state.strip()) + "%20" \
		+ requests.utils.quote(destination_zipcode.strip()) + "%20" \
		+ ".json?access_token=" + access_token;

		req = requests.get(locate_url)

		lon, lat = (req.json())["features"][0]["center"]

		# Store said location

		ride_item.destination_coordinates_lat = lat
		ride_item.destination_coordinates_lon = lon
		ride_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0006_auto_20200224_1233'),
    ]

    operations = [
	migrations.RunPython(updateLocations)
    ]
