# Generated by Django 2.2.5 on 2020-02-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0007_auto_20200224_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideitem',
            name='ride_category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='rideSharing.RideCategory'),
            preserve_default=False,
        ),
    ]
