# Generated by Django 3.1 on 2020-08-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0008_auto_20200226_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rideitem',
            name='start_coordinates_lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rideitem',
            name='start_coordinates_lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='rideitem',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
