# Generated by Django 2.2.5 on 2020-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0009_rideitem_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideitem',
            name='start_coordinates_lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rideitem',
            name='start_coordinates_lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='rideitem',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
