# Generated by Django 2.2.5 on 2020-09-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0009_auto_20200827_1225'),
        ('rideSharing', '0010_auto_20200405_1309'),
    ]

    operations = [
    ]
