# Generated by Django 3.0.5 on 2020-11-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0011_merge_20200918_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideitem',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
