# Generated by Django 3.0.5 on 2020-11-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideSharing', '0012_rideitem_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideitem',
            name='archivedType',
            field=models.CharField(choices=[('VI', 'Visible'), ('HD', 'Hidden'), ('RE', 'Removed'), ('AR', 'Archived')], default='VI', max_length=2),
        ),
    ]
