# Generated by Django 3.1.1 on 2021-04-04 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('item_title', models.CharField(max_length=200)),
                ('item_description', models.CharField(blank=True, max_length=1500)),
                ('item_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('views', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('archivedType', models.CharField(choices=[('VI', 'Visible'), ('HD', 'Hidden'), ('RE', 'Removed'), ('AR', 'Archived')], default='VI', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItemPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='catalog/%Y/%m/%d/')),
                ('position', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('item', 'position')},
            },
        ),
    ]
