# Generated by Django 2.2.5 on 2019-09-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='first_name',
            field=models.CharField(default='firstName_null', max_length=25),
            preserve_default=False,
        ),
    ]
