# Generated by Django 3.2.7 on 2021-11-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
