# Generated by Django 2.2.6 on 2019-11-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogitem_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='first_name',
        ),
    ]
