# Generated by Django 2.2.5 on 2020-03-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_catalogitem_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
