# Generated by Django 3.1 on 2020-08-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_catalogitem_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='item_description',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
