# Generated by Django 2.2.5 on 2020-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200405_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
