# Generated by Django 2.2.5 on 2020-09-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_catalogitem_reported'),
        ('catalog', '0006_catalogitem_reported'),
    ]

    operations = [
    ]
