# Generated by Django 3.0.5 on 2020-11-26 04:03

from django.db import migrations, models
import django.db.models.deletion

def transfer_picture(apps, schema_editor):
    CatalogItem = apps.get_model('catalog', 'CatalogItem')
    CatalogItemPicture = apps.get_model('catalog', 'CatalogItemPicture')
    for item in CatalogItem.objects.all():
        CatalogItemPicture.objects.create(picture=item.item_picture, item=item, position=1 )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201110_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItemPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='catalog/%Y/%m/%d/')),
                ('position', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='catalog.CatalogItem')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('item', 'position')},
            },
        ),

        migrations.RunPython(transfer_picture),

        migrations.RemoveField(
            model_name='catalogitem',
            name='item_picture',
        ),
    ]
