# Generated by Django 3.1.2 on 2021-01-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20201125_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
