# Generated by Django 2.2.5 on 2019-10-30 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
