# Generated by Django 2.2.6 on 2019-10-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='common_destination_zipcode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
