# Generated by Django 2.2.5 on 2019-10-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='preferred_name',
            field=models.CharField(default='Carlito', max_length=50),
        ),
    ]
