# Generated by Django 2.2.5 on 2019-10-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0004_user_profile_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='home_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='home_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='account/profilepics/'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
