# Generated by Django 3.1 on 2020-09-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_auto_20191029_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='last_email',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
