# Generated by Django 3.1.2 on 2021-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_auto_20210924_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='digest',
            field=models.BooleanField(default=True),
        ),
    ]
