# Generated by Django 3.1.2 on 2021-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_auto_20191029_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='banned_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='emails_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='flags_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_email',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_flag',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
