# Generated by Django 3.1.2 on 2022-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0006_user_profile_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='lastDigest',
            field=models.DateTimeField(null=True),
        ),
    ]
