# Generated by Django 3.1 on 2020-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0006_user_profile_last_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='emails_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='last_email',
            field=models.DateTimeField(),
        ),
    ]
