# Generated by Django 2.2.5 on 2020-09-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0006_user_profile_last_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='emails_today',
            field=models.IntegerField(default=0),
        ),
    ]
