# Generated by Django 3.1.2 on 2022-02-13 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0007_user_profile_lastdigest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='lastDigest',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
