# Generated by Django 2.2.5 on 2020-09-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0007_user_profile_emails_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='last_email',
            field=models.DateTimeField(),
        ),
    ]
