# Generated by Django 2.2.5 on 2020-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0008_auto_20200911_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
