# Generated by Django 2.2.5 on 2020-09-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0010_auto_20200914_1753'),
        ('accountant', '0008_auto_20200914_1822'),
    ]

    operations = [
    ]
