# Generated by Django 3.1.2 on 2020-10-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0011_merge_20200918_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='flags_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='last_flag',
            field=models.DateTimeField(null=True),
        ),
    ]
