# Generated by Django 3.1.2 on 2020-11-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0012_auto_20201030_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='banned_until',
            field=models.DateTimeField(null=True),
        ),
    ]
