# Generated by Django 3.1.1 on 2021-04-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('rideSharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideModerationActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('AP', 'Approve'), ('DY', 'Deny'), ('RM', 'Remove')], default='DY', max_length=2)),
                ('reason', models.CharField(max_length=255)),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideSharing.rideitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemModerationActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('AP', 'Approve'), ('DY', 'Deny'), ('RM', 'Remove')], default='DY', max_length=2)),
                ('reason', models.CharField(max_length=255)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogitem')),
            ],
        ),
    ]
