# Generated by Django 3.1.5 on 2021-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmoderationactions',
            name='action_type',
            field=models.CharField(choices=[('AP', 'Approve'), ('DY', 'Deny'), ('RM', 'Remove')], default='DY', max_length=2),
        ),
        migrations.AlterField(
            model_name='ridemoderationactions',
            name='action_type',
            field=models.CharField(choices=[('AP', 'Approve'), ('DY', 'Deny'), ('RM', 'Remove')], default='DY', max_length=2),
        ),
    ]
